### ISSUE TITLE
super-save disable when file header is present.

### ISSUE THREAD

**Issue by skovuri41** [bbatsov/super-save#10]
Hi 
while using  org-crypt and when super-save is enabled the entries in org-mode file gets encrypted every time based on super-save settings/triggers. As I have (org-crypt-use-before-save-magic) turned on.

For auto-save we have header like:
# -_\- buffer-auto-save-file-name: nil; -_-

which will disable auto-save for the particular file worked on.

How can we achieve the same with super-save? i.e disable super-save for just the file working on.
tips and pointers appreciated. thanks.

**Comment by bbatsov** [comment]
I think you need something like `# -*- mode: Org; eval: (super-save-mode 0) -*- #`

**Comment by bbatsov** [comment]
More details - https://stackoverflow.com/questions/19501447/emacs-disabling-a-minor-mode-from-a-file-header
