### ISSUE TITLE
Can't use default spacemacs shortcuts to change windows

### ISSUE THREAD

**Issue by arthurbragaa** [bbatsov/super-save#11]
Hi @bbatsov.
First of all, thank you for this awesome plugin.
I'm using spacemacs and after installing super-save i can't change windows using the default shortcuts.
I get the following error when i press **SPC w h**(Move to window on the left) or **SPC w l**(Move to window on the right):

`
  Debugger entered--Lisp error: (wrong-number-of-arguments (1 . &rest) 0)
  super-save-command-advice()
  apply(super-save-command-advice nil)
  windmove-right()
  evil-window-right(1)
  call-interactively(evil-window-right nil nil)
  command-execute(evil-window-right)
`

I tried some workarounds but none of them worked.
Do you have any ideia of what is causing this?

Thank you very much.

**Comment by grammati** [comment]
Fixed by #12

**Comment by arthurbragaa** [comment]
Thank you @grammati. It's working perfectly.
