### ISSUE TITLE
[feature request] worked with ace-window.

### ISSUE THREAD

**Issue by zw963** [bbatsov/super-save#14]
[ace-window](https://github.com/abo-abo/ace-window) is a easy way switch multi-window/frame quickly.

![picture](http://oremacs.com/download/ace-window.gif)

Thanks.

**Comment by nickserv** [comment]
Have you looked at `super-save-triggers` in `M-x customize-variable`? The triggers include `other-window` by default, so you should be able to replace that entry with `ace-window`.

**Comment by zw963** [comment]
I have done this myself, thanks
