### ISSUE TITLE
Save when idle not working?

### ISSUE THREAD

**Issue by dbarros** [bbatsov/super-save#15]
Is the super-save package also intended to work in non-GUI Emacs (terminal) when using the idle option?

I followed the installation instructions, including refreshing the packages. 

Added the following to my init.el:

```
 (add-to-list 'load-path "~/.emacs.d/elpa/super-save-20160426.729")
 (require 'super-save)
 (super-save-mode +1)
 (setq super-save-auto-save-when-idle t)
```

When switching buffers it saves, but when the default 5 seconds of idle time passed, it never saves buffers.

Any help would be appreciated.

Diego.

**Comment by bbatsov** [comment]
You have to enable `super-save-auto-save-when-idle` before enabling the mode.
