### ISSUE TITLE
super-save isn't working with the window-numbering package

### ISSUE THREAD

**Issue by ghost** [bbatsov/super-save#17]
Hello,

I'm using Spacemacs and it has a feature to number all Emacs windows from 1, 2, 3... using the window-numbering package: https://github.com/nschum/window-numbering.el

When editing a file with super-save is enabled, the file is not automatically saved when I move the cursor to a new window by using the `select-window-...` function from `window-numbering.el` package.

Given the code of the core function of `select-window-by-number` as follow, can you advise how to hook `super-save` with the code that changes the window `(setq window (aref windows i))`?

```
(defun select-window-by-number (i &optional arg)
  "Select window given number I by `window-numbering-mode'.
If prefix ARG is given, delete the window instead of selecting it."
  (interactive "P")
  (let ((windows (car (gethash (selected-frame) window-numbering-table)))
        window)
    (if (and (>= i 0) (< i 10)
             (setq window (aref windows i)))
        (if arg
            (delete-window window)
          (select-window window))
      (error "No window numbered %s" i))))
```

Thanks!

**Comment by bbatsov** [comment]
I guess you just need this in your config:

```
(add-to-list 'super-save-triggers 'select-window-by-number)
```
