### ISSUE TITLE
Would it be possible to completely disable all modification notices?

### ISSUE THREAD

**Issue by alienbogart** [bbatsov/super-save#28]
I tried `  (set-buffer-modified-p nil)` `(setq set-buffer-modified-p nil)` but it doesn't seem to work.

**Comment by zino299792** [comment]
TL; DR
```
(defun suppress-message-advice (old-func &rest args)
  "Stop logging and displaying saving related messages in echo area.
Explicitly call OLD-FUNC with ARGS"
  (let (message-log-max)
    (with-temp-message (or (current-message) "")
      (apply old-func args))))

(use-package super-save
  :diminish
  :config
  (super-save-mode t)
  (advice-add 'super-save-command :around 'suppress-message-advice)
  (setq super-save-auto-save-when-idle t))
```

More details: `super-save` produces two kinds of messages, "Saving file ..." invoked by `save-buffer`; "Wrote ..." by `write-region` C primitive when Emacs actually writes the file to disk. Disable these two altogether when `super-save` does its work should be a sane decision

**Comment by alienbogart** [comment]
That works, thanks!
