### ISSUE TITLE
Turn into a proper minor mode

### ISSUE THREAD

**Issue by swsnr** [bbatsov/super-save#3]
Please turn that into a proper global minor mode that can be enabled and disabled again.

**Comment by manuel-uberti** [comment]
:+1: yes please!

**Comment by bbatsov** [comment]
Yeah, this will probably be the best course of action.

**Comment by manuel-uberti** [comment]
Thank you!

**Comment by swsnr** [comment]
@bbatsov Yes, thanks a lot!
