### ISSUE TITLE
How to stop saving on mouse left click

### ISSUE THREAD

**Issue by rrittwikc** [bbatsov/super-save#34]
Super-save is saving the current modified buffer when I left click the mouse anywhere in the text.

Is there a way to stop this behavior?

**Comment by bbatsov** [comment]
You should just modify `super-save-hook-triggers`. It's default is:

```elisp
(defcustom super-save-hook-triggers
  '(mouse-leave-buffer-hook focus-out-hook)
  "A list of hooks which would trigger `super-save-command'."
  :group 'super-save
  :type '(repeat symbol)
  :package-version '(super-save . "0.3.0"))
```

Removing `mouse-leave-buffer-hook` should do it for you.

**Comment by rrittwikc** [comment]
Thanks. It works.

Also thanks for super-save, it is really useful. I am closing the issue.
