### ISSUE TITLE
Disabling super-save-max-buffer-size (confusing new behavior)

### ISSUE THREAD

**Issue by jakebox** [bbatsov/super-save#39]
Hi,

What would be a good way to not use `super-save-max-buffer-size`? For the past few days I've been confused why a file I often edit was not saving how it used too — after some investigation I see that it is because (I think) of the new `super-save-max-buffer-size` from this commit #37.

I can't set it to nil to disable. I guess I can just make it a really big number but that doesn't feel so neat.

Thanks. One of my favorite little Emacs packages.

**Comment by bbatsov** [comment]
Yeah, I agree that setting this to `nil` should disable it.

**Comment by bbatsov** [comment]
I've also set this to `nil` by default, as it seems that the 10,000 character default was extremely conservative. I guess I didn't pay much attention to this value during the code review. Sorry about this!

**Comment by jakebox** [comment]
No problem, thank you for the quick reply and fix, and for the package! You do good work.

**Comment by cruegge** [comment]
Isn't the predicate `(and super-save-max-buffer-size (< (buffer-size) super-save-max-buffer-size))` incorrect? When the option is `nil`, it disables saving, not the check.

**Comment by bbatsov** [comment]
@cruegge Oh, damn - yeah, it seems all the predicates have to be true for something to be saved. I'm starting to wonder if that's a good design. :-)
